var mongoose = require('mongoose');

var schema = mongoose.Schema;

var apdate = new Date();

 
var registeredSchema = new schema({
    
    _id:{
        type:String,
        required:true,
    },
    firstname:{
        type:String,
        required:true,
    },
    lastname:{
        type:String,
        required:true,
    },
    semester:{
        type:String,
        required:true,
    },
    branch:{
        type:String,
        required:true,
    },
    Email:{
        type:String,
        required:true,
    },
    mobile:{
        type:String,
        required:true,
    },
    cf1name:{
        type:String,
        required:true,
    },
    cf1lname:{
        type:String,
        required:true,
    },
    cf1sem:{
        type:String,
        required:true,
    },
    cf1branch:{
        type:String,
        required:true,
    },
    Email1:{
        type:String,
        required:true,
    },
    mobile1:{
        type:String,
        required:true,
    },
    NSSIAN1:{
        type:String,
        required:true,
    },
    cf2name:{
        type:String,
    },
    cf2lname:{
        type:String,
    },
    cf2sem:{
        type:String,
    },
    cf2branch:{
        type:String,
    },
    Email2:{
        type:String,
    },
    mobile2:{
        type:String,
    },
    NSSIAN2:{
        type:String,
    },
    cf3name:{
        type:String,
    },
    cf3lname:{
        type:String,
    },
    cf3sem:{
        type:String,
    },
    cf3branch:{
        type:String,
    },
    Email3:{
        type:String,
    },
    mobile3:{
        type:String,
    },
    NSSIAN3:{
        type:String,
    },
    cf4name:{
        type:String,
    },
    cf4lname:{
        type:String,
    },
    cf4sem:{
        type:String,
    },
    cf4branch:{
        type:String,
    },
    Email4:{
        type:String,
    },
    mobile4:{
        type:String,
    },
    NSSIAN4:{
        type:String,
    },
    cf5name:{
        type:String,
    },
    cf5lname:{
        type:String,
    },
    cf5sem:{
        type:String,
    },
    cf5branch:{
        type:String,
    },
    Email5:{
        type:String,
    },
    mobile5:{
        type:String,
    },
    NSSIAN5:{
        type:String,
    },
    company:{
        type:String,
        required:true,
    },
    website:{
        type:String,
        required:true,
    },
    employee:{
        type:String,
        required:true,
    },
    desc1:{
        type:String,
        required:true,
    },
    whopay:{
        type:String,
        required:true,
    },
    custpain:{
        type:String,
        required:true,
    },
    Competitors:{
        type:String,
        required:true,
    },
    UVP:{
        type:String,
        required:true,
    },
    solution:{
        type:String,
        required:true,
    },
    copyright:{
        type:String,
        required:true,
    },
    customers:{
        type:String,
        required:true,
    },
    marketing:{
        type:String,
        required:true,
    },
    makemoney:{
        type:String,
        required:true,
    },
    investment:{
        type:String,
        required:true,
    },
    Goals:{
        type:String,
        required:true,
    },
    applydate:{
        type:String,
        default:apdate,
    },
    presentdateyes:{
        type:Boolean,
        default:false,
    },
    presentdate:{
        type:String,
    },
    reviewyes:{
        type:Boolean,
        default:false,
    },
    reviewdate:{
        type:String,
    },
    registeredyes:{
        type:Boolean,
        default:false,
    },
    registereddate:{
        type:String,
    },
    mentor:{
        type:String,
        required:true,
    },
}, {collection: 'registered'});


module.exports = mongoose.model('registered',registeredSchema,'registered');
    